FROM quay.io/fedora/fedora-coreos:testing

COPY rhcontainerbot-podman-next-fedora.repo /etc/yum.repos.d/
COPY rhcontainerbot-podman-next-fedora.gpg /etc/pki/rpm-gpg/

# Replace aardvark-dns, conmon, crun, netavark, podman, containers-common
# Remove moby-engine, containerd, runc, zincati ?
# Note: Currently does not result in a size reduction for the container image

RUN rpm-ostree override replace --experimental --freeze \
    --from repo="copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next" \
    aardvark-dns crun netavark podman containers-common containers-common-extra crun-wasm && \
    rpm-ostree override remove moby-engine containerd runc && \
    ostree container commit

RUN rpm-ostree install subscription-manager && rm -fr /var/cache
